<?php
   
   $schedules =[ 
       "09:00" =>[
            [
                "id"=>"09:15",
                "status"=>"busy"
            ],
            [
                "id"=>"09:30",
                "status"=>"busy"
            ],
            [
                "id"=>"09:45",
                "status"=>"available"
            ],
            [
                "id"=>"10:00",
                "status"=>"busy"
            ],
       ], 
        "10:00"=>[
            ["id"=>"10:15",
             "status"=>"available"
            ],
            ["id"=>"10:30",
             "status"=>"busy"
            ],
            ["id"=>"10:45",
             "status"=>"available"
            ],
            ["id"=>"11:00",
             "status"=>"busy"
            ]
        ], 
        "11:00"=>[
            ["id"=>"11:15",
             "status"=>"available"
            ],
            ["id"=>"11:30",
             "status"=>"busy"
            ],
            ["id"=>"11:45",
             "status"=>"available"
            ],
            ["id"=>"12:00",
             "status"=>"busy"
            ]
        ],
        "12:00"=>[
            ["id"=>"12:15",
             "status"=>"available"
            ],
            ["id"=>"12:30",
             "status"=>"busy"
            ],
            ["id"=>"12:45",
             "status"=>"available"
            ],
            ["id"=>"13:00",
             "status"=>"busy"
            ]
        ], 
        "13:00"=>[
            ["id"=>"13:15",
             "status"=>"available"
            ],
            ["id"=>"13:30",
             "status"=>"busy"
            ],
            ["id"=>"13:45",
             "status"=>"available"
            ],
            ["id"=>"14:00",
             "status"=>"busy"
            ]
        ], 
        "14:00"=>[
            ["id"=>"14:15",
             "status"=>"available"
            ],
            ["id"=>"14:30",
             "status"=>"busy"
            ],
            ["id"=>"14:45",
             "status"=>"available"
            ],
            ["id"=>"15:00",
             "status"=>"busy"
            ]
        ], 
        "15:00"=>[
            ["id"=>"15:15",
             "status"=>"available"
            ],
            ["id"=>"15:30",
             "status"=>"busy"
            ],
            ["id"=>"15:45",
             "status"=>"available"
            ],
            ["id"=>"16:00",
             "status"=>"busy"
            ]
        ], 
        "16:00"=>[
            ["id"=>"16:15",
             "status"=>"available"
            ],
            ["id"=>"16:30",
             "status"=>"busy"
            ],
            ["id"=>"16:45",
             "status"=>"available"
            ],
            ["id"=>"17:00",
             "status"=>"busy"
            ]
        ], 
        "17:00"=>[
            ["id"=>"17:15",
             "status"=>"available"
            ],
            ["id"=>"17:30",
             "status"=>"busy"
            ],
            ["id"=>"17:45",
             "status"=>"available"
            ],
            ["id"=>"18:00",
             "status"=>"busy"
            ]
        ], 
        "18:00"=>[
            ["id"=>"18:15",
             "status"=>"available"
            ],
            ["id"=>"18:30",
             "status"=>"busy"
            ],
            ["id"=>"18:45",
             "status"=>"available"
            ],
            ["id"=>"19:00",
             "status"=>"busy"
            ]
        ], 
        "19:00"=>[
            ["id"=>"19:15",
             "status"=>"available"
            ],
            ["id"=>"19:30",
             "status"=>"busy"
            ],
            ["id"=>"19:45",
             "status"=>"available"
            ],
            ["id"=>"20:00",
             "status"=>"busy"
            ]
        ], 
        "20:00"=>[
            ["id"=>"20:15",
             "status"=>"available"
            ],
            ["id"=>"20:30",
             "status"=>"busy"
            ],
            ["id"=>"20:45",
             "status"=>"available"
            ],
            ["id"=>"21:00",
             "status"=>"busy"
            ]
        ]
         ]
?>

@extends("layouts.layout")
    @section("content")
        <div class="container">
            <div class="chart">
                <div class=" chart-period">
                @foreach ($schedules  as $time => $schedule)
                    <div><span>{{$time}}</span></div>
                @endforeach
                </div>
                <div class="chart-row">
                @foreach ($schedules as  $time => $schedule )
                    <div class="window">
                    @foreach ($schedule as $period)
                         <div 
                         onclick="alert('{!! $period['id'] !!}')" 
                         class={{$period["status"]=="busy" ? "red" : "green" }}></div>
                    @endforeach
                   </div>
                @endforeach
                </div>
            </div>
        </div>
    @stop