@extends("layouts.layout")
@section("content")
    @include("layouts.home-slider")
    @include("layouts.services")
    @include("layouts.whytrustus")
    @include("layouts.our-doctors")
    @include("layouts.section-appointment")
    @include("layouts.feedbacks")
@stop